### ISSUE TITLE
Unintended Correlations API Response

### ISSUE THREAD

**Issue by cutehammond772** [SWM-Thlee/linked-paper-search#47]
## 개요

- 특정 논문에 대한 유사 논문을 일정 개수 가져오는 API에 대한 이슈이다.
- 현재, 의도 상에서는 특정 논문까지 같이 포함하여 데이터를 반환하는 방식이다.
- 그러나, 실제 결과를 보았을 때 자기 자신이 포함되지 않은 상태로 응답이 반환되는 상태이다.

## 내용

> [API 응답 예시](https://api.linked-paper.com/correlations/727b9e364ca56ce4695dab748efe21620917abb1312e02f9f9e3070c266244a6)

- 위의 API 응답 예시의 경우, 자기 자신의 논문이 포함되고 있지 않는 것을 알 수 있다.
- 해당 응답으로부터 나오는 다른 논문들을 타겟으로 하여 API 호출 시에도 동일하다.

### 1. 유사 논문 API에서 왜 자기 자신을 포함해야 하는가?

- 특정 논문을 타겟으로 유사 논문을 불러올 시, 자기 자신의 경우 유사도가 1(=최대)이므로 실질적으로는 필요 없을 것이라 생각할 수 있다.
- 하지만, 유사 논문을 불러와 뷰에 표시할 때 **타겟이 되는 논문의 정보도 같이 표시될 가능성이 높으므로** 같이 포함되는 것이 더 깔끔하다고 볼 수 있다.

### 2. 유사 논문을 불러올 때 특정 논문에 대한 ID를 미리 알고 있어야 하는데, 그렇다는 건 특정 논문에 대한 정보를 미리 가지고 있지 않은가?

- 일반적으로 그럴 가능성이 높으나, 항상 **그러한 컨텍스트**가 유지되는 것을 보장할 수 없다는 것을 인지해야 한다.
- 예를 들면, 유사 논문을 기반으로 그래프 뷰를 형성할 때까지의 플로우를 생각해 보자.
- 보통, 검색 결과 페이지에서 특정 논문을 Bloom(해당 논문을 기반으로 유사 논문 그래프 뷰 생성)함으로써 그래프 뷰로 이어지게 된다.
- 이 상황에서는, 이전 플로우에서 해당 논문의 데이터가 존재하므로 그대로 넘기는 방식으로 구현할 수 있을 것이다.
- 그러나, 항상 이러한 플로우로 (유사 논문) 그래프 뷰를 형성하는 것은 아닐 수 있다.

간단하게 예시를 들면, 특정 사용자가 링크를 통해 바로 그래프 뷰로 접근하는 플로우를 생각해볼 수 있다.

- 여기서 링크에는 특정 논문의 ID 정보만 포함되어 있기에, API를 호출할 때 특정 논문의 데이터도 같이 받아오도록 해야 한다.

## 제안 (Optional)

- OpenSearch 문제로 특정 논문에 대한 동일한 논문이 나오는 것을 보장할 수 없다면, ID를 가지고 직접 해당 논문을 불러온 다음 응답에 포함하는 방식도 있을 것 같다.

**Comment by ljy2855** [comment]
#51 에서 해당 이슈 해결
